### ISSUE TITLE
Making the Add On available for more Domains (.de for example)

### ISSUE THREAD

**Issue by Morice99** [peterphmikkelsen/audible-volume-control#1]
Hey, i love that you made this Add on, but could you make it also working for `.de` domains and for other people also other domains?

I could write my own Add on, but that would not be fair because you did it first. 

Thanks in advance.

**Comment by peterphmikkelsen** [comment]
> Hey, i love that you made this Add on, but could you make it also working for `.de` domains and for other people also other domains?
> 
> I could write my own Add on, but that would not be fair because you did it first.
> 
> Thanks in advance.

Hey! Thanks for the interest in the add-on! I have added more domains to the manifest (including `.de`) and version 1.1 should be available already. 
ab4bc39

**Comment by Morice99** [comment]
Works great! 

Thank you a lot :)
